### ISSUE TITLE
Maui .net 8 Preview 7 your project no longer works (MAUI BUG)

### ISSUE THREAD

**Issue by gabsamples6** [AndreasReitberger/SharedMauiXamlStyles#247]
Hi
I got inspired by your approach many months ago on how to share styles.. I now get an issue with my project when converting to .net 8,and my approach is similar to  yours.
Is it ok with you if I raise a issue on the maui repo and point to this solution as example or upload your solution as converted .net 8 project? 

It will save a lot of time in creating a repo
thanks

**Comment by AndreasReitberger** [comment]
Hi @gabsamples6 
Sure, feel free to do so :) thanks!

**Comment by AndreasReitberger** [comment]
Seems to be fixed in the latest build? If you confirm, please close this issue :)
Also feel free to open a PR for the `net8` migration.
Thanks!

**Comment by gabsamples6** [comment]
All fixed in latest build .thanks!
